<?php

namespace GameBundle\Repository;

/**
 * ColonneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ColonneRepository extends \Doctrine\ORM\EntityRepository
{
}
