<?php

namespace GameBundle\Repository;

/**
 * GridRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GridRepository extends \Doctrine\ORM\EntityRepository
{
    public function getHydratedGrid($id)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('g')
            ->from('GameBundle:Grid', 'g')
            ->leftJoin('g.colonnes', 'c')
            ->addSelect('c')
            ->leftJoin('c.slots', 's')
            ->addSelect('s')
            ->leftJoin('s.player', 'p')
            ->addSelect('p')
            ->leftJoin('g.lignes', 'l')
            ->addSelect('l')
            ->where('g.id = ?1')
            ->setParameter(1, $id);
        return $qb->getQuery()->getResult()[0];
    }

}
